# VERİTABANI BİLGİLERİNİ DOĞRU GİRİNİZ
# VERİTABANINA BAĞLANMAZ İSE EKLENTİ DEVRE DIŞI KALICAKTIR.
# Eğer webhosting'e bağlamak isterseniz makinanızın ip adresini cpanel kısmından uzak MySQL'e girmeyi unutmayın.

# AYRICA EKLENTİNİN KAYNAK KODUNA ULAŞMAK İÇİN https://github.com/EmirhanBarlas/MailVerify
# STAR ATMAYI UNUTMAYINIZ = )

mysql:
  host: "localhost"
  port: "3306"
  database: "splendidnwcom_sp"
  username: "root"
  password: ""
  table: "emails"

messages:
  success_message: "&aE-posta adresiniz başarıyla kaydedildi."
  invalid_email_message: "&cGirdiğiniz e-posta adresi gecersizdir."
  usage_message: "&cDoğru kullanım: /eposta <e-posta>"
  player_only_message: "&cBu komutu yalnızca bir oyuncu kullanabilir."
  email_not_verified_warning: "&cE-posta adresinizi doğrulamadığınız için belirli bir süre içinde sunucudan atılacaksınız. &8(&e/eposta <e-posta>&8) &aile tekrar deneyebilirsiniz."
  kick_message: "&cE-posta adresinizi doğrulamadığınız için sunucudan atıldınız."
  reload_message: "&aYapılandırma dosyası yeniden yüklendi."

kick_delay_minutes: 1

discord:
  webhook_url: "https://discord.com/api/webhooks/1197584423823081503/p-y-hp1SmZMnzpfipLOaa8tjIH4gMz803Mm1hOvrscFknaKb11Ck83CJamMuxg8tVJ5C"