name: MailVerify
author: _Barlas_
version: '${project.version}'
main: org.splendid.mailverify.MailVerify
api-version: '1.16'

commands:
  eposta:
    description: Oyuncunun e-posta adresini doğrular.
    usage: /eposta <e-posta_adresi>
  reload:
    description: Yapılandırma dosyasını yeniden yükle.
    usage: /reload
    permission: mailverify.reload

permissions:
  mailverify.use:
    description: E-posta doğrulama komutunu kullanma izni.
    default: true